<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="System.Management.Automation" Version="[7.4.20]" />
    <PackageVersion Include="LibTmux" Version="[0.0.0-ci.1791642867347.1994485671]" />
    <PackageVersion Include="LibTmux.Query.Json" Version="[0.0.0-ci.1791642867347.1994485671]" />
    <PackageVersion Include="LibTmux.Workspace" Version="[0.0.0-ci.1791642867347.1994485671]" />
    <PackageVersion Include="YamlDotNet" Version="[18.1.0]" />
  </ItemGroup>
</Project>
