<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>LibTmux.StandaloneCoreBenchmark</AssemblyName>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <RestorePackagesWithLockFile>false</RestorePackagesWithLockFile>
    <ManagePackageVersionsCentrally>false</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Reference Include="LibTmux">
      <HintPath>$(CoreLibraryDirectory)/LibTmux.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="LibTmux.Query.Json">
      <HintPath>$(CoreLibraryDirectory)/LibTmux.Query.Json.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>$(CoreLibraryDirectory)/Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.DependencyInjection.Abstractions">
      <HintPath>$(CoreLibraryDirectory)/Microsoft.Extensions.DependencyInjection.Abstractions.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
